namespace Singulink.Threading;

/// <summary>
/// Provides various convenience lock-free atomic "spin" operations.
/// </summary>
/// <remarks>
/// <para>The methods provided here try to perform the requested operation without a lock and keep retrying if a competing thread modifies the value first.
/// These methods are fully compatible with <see cref="Interlocked"/> and <see cref="Volatile"/> methods on the same locations and can be used in conjunction
/// with them as needed.</para>
/// </remarks>
public static class InterlockedSpin
{
    /// <inheritdoc cref="Exchange{T}(ref T, out T, Func{T, T})"/>
    public static T Exchange<T>(ref T location, Func<T, T> newValueFactory) where T : class => Exchange(ref location, out _, newValueFactory);

    /// <summary>
    /// Replaces a value with a new value generated by a factory function.
    /// </summary>
    /// <param name="location">The location to be exchanged.</param>
    /// <param name="originalValue">When this method returns, contains the original value at the specified location.</param>
    /// <param name="newValueFactory">A function that generates a new value based on the original value.</param>
    /// <returns>The new value that was set at the specified location.</returns>
    public static T Exchange<T>(ref T location, out T originalValue, Func<T, T> newValueFactory) where T : class
    {
        T newValue;

        do {
            originalValue = Volatile.Read(ref location);
            newValue = newValueFactory.Invoke(originalValue);

            if (ReferenceEquals(originalValue, newValue))
                return newValue;
        }
        while (Interlocked.CompareExchange(ref location, newValue, originalValue) != originalValue);

        return newValue;
    }

    /// <inheritdoc cref="TryIncrementToMax(ref int, int, out int)"/>
    public static bool TryIncrementToMax(ref int location, int maxValue) => TryIncrementToMax(ref location, maxValue, out _);

    /// <summary>
    /// Attempts to increment the specified value up to a maximum value.
    /// </summary>
    /// <param name="location">The location to be incremented.</param>
    /// <param name="maxValue">The maximum value to which the location can be incremented.</param>
    /// <param name="newValue">When this method returns, contains the new value if the increment was successful, or the current value if the
    /// maximum was reached.</param>
    /// <returns><see langword="true"/> if the value was successfully incremented; otherwise, <see langword="false"/> if the current value is already at or
    /// above the maximum value.</returns>
    public static bool TryIncrementToMax(ref int location, int maxValue, out int newValue)
    {
        int currentValue;

        do {
            currentValue = Volatile.Read(ref location);

            if (currentValue >= maxValue)
            {
                newValue = currentValue;
                return false;
            }
        }
        while (Interlocked.CompareExchange(ref location, currentValue + 1, currentValue) != currentValue);

        newValue = currentValue + 1;
        return true;
    }

    /// <inheritdoc cref="TryDecrementToMin(ref int, int, out int)"/>
    public static bool TryDecrementToMin(ref int location, int minValue) => TryDecrementToMin(ref location, minValue, out _);

    /// <summary>
    /// Attempts to decrement the specified value up to a maximum value.
    /// </summary>
    /// <param name="location">The location to be decremented.</param>
    /// <param name="minValue">The minimum value to which the location can be decremented.</param>
    /// <param name="newValue">When this method returns, contains the new value if the decrement was successful, or the current value if the
    /// minimum was reached.</param>
    /// <returns><see langword="true"/> if the value was successfully decremented; otherwise, <see langword="false"/> if the current value is already at or
    /// below the minimum value.</returns>
    public static bool TryDecrementToMin(ref int location, int minValue, out int newValue)
    {
        int currentValue;

        do
        {
            currentValue = Volatile.Read(ref location);

            if (currentValue <= minValue)
            {
                newValue = currentValue;
                return false;
            }
        }
        while (Interlocked.CompareExchange(ref location, currentValue - 1, currentValue) != currentValue);

        newValue = currentValue - 1;
        return true;
    }
}
